[pytest]
minversion = 7.0
addopts = -ra -q --strict-markers
testpaths = tests/acceptance
markers =
    smoke: marks tests as smoke tests
    integration: marks tests as integration tests
    skip_unimplemented: marks tests for unimplemented features
python_files = test_*.py
python_classes = Test*
python_functions = test_*